name: Test

on: [push, pull_request]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11"]
            fail-fast: false

        steps:
        - uses: actions/checkout@v3
        - name: Install poetry
          run: pipx install poetry
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            cache: poetry
        - name: Install Python dependencies
          run: poetry install
        - name: Lint with flake8
          run: |
            poetry run flake8 --version
            poetry run flake8 --show-source --statistics evtstrd evtstrd_test
        - name: Type check with mypy
          run: |
            poetry run mypy --version
            poetry run mypy evtstrd evtstrd_test
        - name: Test with unittest
          run: poetry run python -Wall -m unittest discover -t . -s evtstrd_test -p "*.py"
