name: Test

on: [push, pull_request]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11", "3.12"]
            fail-fast: false

        steps:
        - uses: actions/checkout@v3
        - name: Install poetry
          run: pipx install poetry
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            allow-prereleases: true
            cache: poetry
        - name: Install Python dependencies
          run: poetry install
        - name: Lint with ruff
          run: poetry run poe lint
        - name: Type check with mypy
          run: poetry run poe typecheck
        - name: Test with unittest
          run: poetry run poe test
